const SpotlightData = [
  {
    id: 1,
    cover: "img/card-1.jpg",
    category: "Luxury Travel",
    title: "Three Days, One Carry-On",
    desc: "A tight edit of outfits and essentials for a polished city break—no extras, no stress.",
    author: "Sofia Martins",
    date: "Apr 2026",
    readTime: "4 min read",
  },
  {
    id: 2,
    cover: "img/card-2.jpg",
    category: "Watches",
    title: "Modern Classics, Quietly Done",
    desc: "Design cues that never shout: clean dials, restrained metal tones, and perfect proportions.",
    author: "Noah Reed",
    date: "Apr 2026",
    readTime: "5 min read",
  },
  {
    id: 3,
    cover: "img/card-3.jpg",
    category: "Fine Living",
    title: "Small Details That Feel Expensive",
    desc: "From linens to lighting—micro upgrades that change the whole mood of a space.",
    author: "Ava Chen",
    date: "Mar 2026",
    readTime: "6 min read",
  },
  {
    id: 4,
    cover: "img/card-4.jpg",
    category: "Style Notes",
    title: "The 10-Minute Outfit Formula",
    desc: "A repeatable styling system that keeps silhouettes sharp and colors intentional.",
    author: "Mila Laurent",
    date: "Mar 2026",
    readTime: "3 min read",
  },
  {
    id: 5,
    cover: "img/blog2.jpg",
    category: "Destinations",
    title: "Boutique Hotels Worth Booking",
    desc: "A shortlist of stays with character, calm, and an eye for detail—without the noise.",
    author: "Jasmin Smith",
    date: "Feb 2026",
    readTime: "7 min read",
  },
  {
    id: 6,
    cover: "img/blog3.jpg",
    category: "Interiors",
    title: "A Home That Feels Like a Suite",
    desc: "Layered textures, soft contrast, and negative space—luxury through restraint.",
    author: "Ethan Cole",
    date: "Feb 2026",
    readTime: "5 min read",
  },
];
export default SpotlightData;
